TRAIN:
  BATCH_SIZE: 32
  N_EPOCHS: 50
  SAVE_FREQ: 25
  LEARNING_RATE: 1e-4
  LR_MILESTONES: [50]
  GAMMA: .5
  BETAS: (.9, .999)
  WEIGHT_DECAY: 0
NETWORK:
  N_SAMPLING_POINTS: 2048
  GRIDDING_LOSS_SCALES: [128]
  GRIDDING_LOSS_ALPHAS: [0.1]
DIR:
  OUT_PATH: './output'
CONST:
  DEVICE: '0'
  NUM_WORKERS: 8
  N_INPUT_POINTS: 2048
